name: CI/CD Pipeline

on:
    push:
        branches:
            [main]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to repo
              uses: actions/checkout@main

            - name: Setup Node
              uses: actions/setup-node@main
            
            - name: Install Dependencies
              run: npm install

            - name: Run Unit Test
              run: npm run test:ci
    
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: [test]
        steps:
            - name: Checkout to repo
              uses: actions/checkout@main

            - name: Setup Node
              uses: actions/setup-node@main

            - name: Install Dependencies
              run: npm install

            - name: Run Build
              run: npm run build

            - name: Create artifact
              uses: actions/upload-artifact@main
              with:
                name: dist
                path: ./dist

    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        needs: [build]

        steps: 
          - name: Checkout to repo
            uses: actions/checkout@main

          - name: Setup Node
            uses: actions/setup-node@main

          - name: Install Dependencies
            run: npm install

          - name: Run Build
            run: npm run build

          - name: Deploy to firebase
            uses: w9jds/firebase-action@master
            with:
                args: deploy --only hosting
            env:
                GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}   